#!C:\Users\brett.layman\Documents\AA-SI\AA-SI_recipe_manager\example_recipes\Workshop_example_recipe_refactor\hb1603_env\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
