"source_filenames": ["HBB_038kHz_18July2016.cal"]
"record_created": "2026-05-20T16:02:27.986625+00:00"
"record_author": "<Your Name>"
"channel": "GPT  38 kHz 0090720346bc 1-1 ES38B"
"transceiver_id": "0090720346bc"
"transceiver_model": "GPT"
"transceiver_ethernet_address": "0090720346bc"
"transceiver_serial_number": null
"transceiver_number": 1
"transceiver_port": 1
"channel_instance_number": 1
"transducer_model": "ES38B"
"transducer_serial_number": null
"pulse_form": "0"
"frequency_start": 38000.0
"frequency_end": 38000.0
"nominal_transducer_frequency": 38000.0
"transmit_power": 1000.0
"transmit_duration_nominal": 0.001024
"multiplexing_found": null
"calibration_date": "2016-07-18"
"calibration_comments": "HB Bigelow EK60 calibration, 38.1-mm WC sphere, Newport Naval\
  \ Anchorage south of bridge, 18 July 2016"
"calibration_version": null
"absorption_indicative": 0.0072
"sound_speed_indicative": 1522.6
"temperature": null
"salinity": null
"acidity": null
"pressure": null
"sample_interval": 0.000128
"transmit_bandwidth": 2430.0
"beam_type": null
"calibration_acquisition_method": null
"sphere_diameter": null
"sphere_material": null
"source_file_type": ".cal"
"source_file_location": null
"sonar_software_version": "2.4.3"
"sonar_software_name": null
"equivalent_beam_angle": -20.6
"gain_correction": [24.06]
"sa_correction": [-0.68]
"frequency": [38000.0]
"beamwidth_transmit_major": [6.97]
"beamwidth_receive_major": [6.97]
"beamwidth_transmit_minor": [6.87]
"beamwidth_receive_minor": [6.87]
"echoangle_major": [-0.02]
"echoangle_minor": [0.07]
"echoangle_major_sensitivity": [21.9]
"echoangle_minor_sensitivity": [21.9]
"source_file_paths": null
