- filename: D20160725-T205832.raw
  file_format: EK60
  metadata_start_time: '2016-07-25T20:58:32'
  first_ping_time: '2016-07-25T20:58:32.586+00:00'
  last_ping_time: '2016-07-25T21:21:21.045+00:00'
  raw0_count: 860
  gps_data:
    first_gps:
      latitude: 41.745935
      longitude: -65.507845
      timestamp: '2016-07-25T20:58:36.881158+00:00'
      nmea_sentence: $GPGGA,205836,4144.7561,N,06530.4707,W,1,10,00.8,21.5,M,-29.0,M,,
    last_gps:
      latitude: 41.813013
      longitude: -65.50362
      timestamp: '2016-07-25T21:21:31.860456+00:00'
      nmea_sentence: $GPGGA,212131,4148.7808,N,06530.2172,W,1,09,00.9,21.0,M,-28.9,M,,
    nmea_count: 3896
    valid_gps_count: 2064
    sentence_types:
    - GPGGA
    - GPGLL
  channels:
  - channel_id: GPT  38 kHz 0090720346bc 1-1 ES38B
    transceiver_id: 0090720346bc
    transceiver_model: GPT
    transceiver_ethernet_address: 0090720346bc
    transceiver_serial_number: null
    transceiver_number: 1
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES38B
    frequency: 38000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 38000.0
    frequency_end: 38000.0
    nominal_transducer_frequency: 38000.0
    multiplexing_found: false
  - channel_id: GPT  18 kHz 009072056b0e 2-1 ES18-11
    transceiver_id: 009072056b0e
    transceiver_model: GPT
    transceiver_ethernet_address: 009072056b0e
    transceiver_serial_number: null
    transceiver_number: 2
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES18-11
    frequency: 18000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 18000.0
    frequency_end: 18000.0
    nominal_transducer_frequency: 18000.0
    multiplexing_found: false
  - channel_id: GPT 120 kHz 0090720580f1 3-1 ES120-7
    transceiver_id: 0090720580f1
    transceiver_model: GPT
    transceiver_ethernet_address: 0090720580f1
    transceiver_serial_number: null
    transceiver_number: 3
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES120-7
    frequency: 120000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 500.0
    pulse_form: '0'
    frequency_start: 120000.0
    frequency_end: 120000.0
    nominal_transducer_frequency: 120000.0
    multiplexing_found: false
  - channel_id: GPT 200 kHz 009072034261 4-1 ES200-7
    transceiver_id: 009072034261
    transceiver_model: GPT
    transceiver_ethernet_address: 009072034261
    transceiver_serial_number: null
    transceiver_number: 4
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES200-7
    frequency: 200000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 300.0
    pulse_form: '0'
    frequency_start: 200000.0
    frequency_end: 200000.0
    nominal_transducer_frequency: 200000.0
    multiplexing_found: false
  - channel_id: GPT  70 kHz 00907206042f 5-1 ES70-7C
    transceiver_id: 00907206042f
    transceiver_model: GPT
    transceiver_ethernet_address: 00907206042f
    transceiver_serial_number: null
    transceiver_number: 5
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES70-7C
    frequency: 70000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 750.0
    pulse_form: '0'
    frequency_start: 70000.0
    frequency_end: 70000.0
    nominal_transducer_frequency: 70000.0
    multiplexing_found: false
  instrument: EK60
- filename: D20160725-T212129.raw
  file_format: EK60
  metadata_start_time: '2016-07-25T21:21:29'
  first_ping_time: '2016-07-25T21:21:29.046+00:00'
  last_ping_time: '2016-07-25T21:44:17.290+00:00'
  raw0_count: 860
  gps_data:
    first_gps:
      latitude: 41.813062
      longitude: -65.503617
      timestamp: '2016-07-25T21:21:32.832740+00:00'
      nmea_sentence: $GPGGA,212132,4148.7837,N,06530.2170,W,1,09,00.9,21.0,M,-28.9,M,,
    last_gps:
      latitude: 41.881715
      longitude: -65.499533
      timestamp: '2016-07-25T21:44:28.044378+00:00'
      nmea_sentence: $GPGGA,214427,4152.9029,N,06529.9720,W,1,09,00.9,27.0,M,-28.8,M,,
    nmea_count: 3921
    valid_gps_count: 2064
    sentence_types:
    - GPGGA
    - GPGLL
  channels:
  - channel_id: GPT  38 kHz 0090720346bc 1-1 ES38B
    transceiver_id: 0090720346bc
    transceiver_model: GPT
    transceiver_ethernet_address: 0090720346bc
    transceiver_serial_number: null
    transceiver_number: 1
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES38B
    frequency: 38000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 38000.0
    frequency_end: 38000.0
    nominal_transducer_frequency: 38000.0
    multiplexing_found: false
  - channel_id: GPT  18 kHz 009072056b0e 2-1 ES18-11
    transceiver_id: 009072056b0e
    transceiver_model: GPT
    transceiver_ethernet_address: 009072056b0e
    transceiver_serial_number: null
    transceiver_number: 2
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES18-11
    frequency: 18000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 18000.0
    frequency_end: 18000.0
    nominal_transducer_frequency: 18000.0
    multiplexing_found: false
  - channel_id: GPT 120 kHz 0090720580f1 3-1 ES120-7
    transceiver_id: 0090720580f1
    transceiver_model: GPT
    transceiver_ethernet_address: 0090720580f1
    transceiver_serial_number: null
    transceiver_number: 3
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES120-7
    frequency: 120000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 500.0
    pulse_form: '0'
    frequency_start: 120000.0
    frequency_end: 120000.0
    nominal_transducer_frequency: 120000.0
    multiplexing_found: false
  - channel_id: GPT 200 kHz 009072034261 4-1 ES200-7
    transceiver_id: 009072034261
    transceiver_model: GPT
    transceiver_ethernet_address: 009072034261
    transceiver_serial_number: null
    transceiver_number: 4
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES200-7
    frequency: 200000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 300.0
    pulse_form: '0'
    frequency_start: 200000.0
    frequency_end: 200000.0
    nominal_transducer_frequency: 200000.0
    multiplexing_found: false
  - channel_id: GPT  70 kHz 00907206042f 5-1 ES70-7C
    transceiver_id: 00907206042f
    transceiver_model: GPT
    transceiver_ethernet_address: 00907206042f
    transceiver_serial_number: null
    transceiver_number: 5
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES70-7C
    frequency: 70000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 750.0
    pulse_form: '0'
    frequency_start: 70000.0
    frequency_end: 70000.0
    nominal_transducer_frequency: 70000.0
    multiplexing_found: false
  instrument: EK60
- filename: D20160725-T214425.raw
  file_format: EK60
  metadata_start_time: '2016-07-25T21:44:25'
  first_ping_time: '2016-07-25T21:44:25.292+00:00'
  last_ping_time: '2016-07-25T22:07:13.564+00:00'
  raw0_count: 860
  gps_data:
    first_gps:
      latitude: 41.881765
      longitude: -65.499538
      timestamp: '2016-07-25T21:44:28.883332+00:00'
      nmea_sentence: $GPGGA,214428,4152.9059,N,06529.9723,W,1,09,00.9,27.1,M,-28.8,M,,
    last_gps:
      latitude: 41.940667
      longitude: -65.4965
      timestamp: '2016-07-25T22:07:25.024582+00:00'
      nmea_sentence: $GPGLL,4156.44,N,06529.79,W,220724,A,A
    nmea_count: 3808
    valid_gps_count: 2066
    sentence_types:
    - GPGGA
    - GPGLL
  channels:
  - channel_id: GPT  38 kHz 0090720346bc 1-1 ES38B
    transceiver_id: 0090720346bc
    transceiver_model: GPT
    transceiver_ethernet_address: 0090720346bc
    transceiver_serial_number: null
    transceiver_number: 1
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES38B
    frequency: 38000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 38000.0
    frequency_end: 38000.0
    nominal_transducer_frequency: 38000.0
    multiplexing_found: false
  - channel_id: GPT  18 kHz 009072056b0e 2-1 ES18-11
    transceiver_id: 009072056b0e
    transceiver_model: GPT
    transceiver_ethernet_address: 009072056b0e
    transceiver_serial_number: null
    transceiver_number: 2
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES18-11
    frequency: 18000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 1000.0
    pulse_form: '0'
    frequency_start: 18000.0
    frequency_end: 18000.0
    nominal_transducer_frequency: 18000.0
    multiplexing_found: false
  - channel_id: GPT 120 kHz 0090720580f1 3-1 ES120-7
    transceiver_id: 0090720580f1
    transceiver_model: GPT
    transceiver_ethernet_address: 0090720580f1
    transceiver_serial_number: null
    transceiver_number: 3
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES120-7
    frequency: 120000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 500.0
    pulse_form: '0'
    frequency_start: 120000.0
    frequency_end: 120000.0
    nominal_transducer_frequency: 120000.0
    multiplexing_found: false
  - channel_id: GPT 200 kHz 009072034261 4-1 ES200-7
    transceiver_id: 009072034261
    transceiver_model: GPT
    transceiver_ethernet_address: 009072034261
    transceiver_serial_number: null
    transceiver_number: 4
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES200-7
    frequency: 200000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 300.0
    pulse_form: '0'
    frequency_start: 200000.0
    frequency_end: 200000.0
    nominal_transducer_frequency: 200000.0
    multiplexing_found: false
  - channel_id: GPT  70 kHz 00907206042f 5-1 ES70-7C
    transceiver_id: 00907206042f
    transceiver_model: GPT
    transceiver_ethernet_address: 00907206042f
    transceiver_serial_number: null
    transceiver_number: 5
    transceiver_port: 1
    channel_instance_number: 1
    transducer_serial_number: null
    transducer_model: ES70-7C
    frequency: 70000.0
    transmit_duration_nominal: 0.0010239999974146485
    transmit_power: 750.0
    pulse_form: '0'
    frequency_start: 70000.0
    frequency_end: 70000.0
    nominal_transducer_frequency: 70000.0
    multiplexing_found: false
  instrument: EK60
